# Generated by Django 3.2.3 on 2022-12-09 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_alter_user_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(default=None, max_length=50, verbose_name='blog code')),
                ('title', models.CharField(default=None, max_length=255, verbose_name='blog title')),
                ('body', models.TextField(default=None, verbose_name='blog content')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('time_updated', models.DateTimeField(auto_now=True, verbose_name='updated time')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_blog', to='user.user')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
            },
        ),
    ]
