# Generated by Django 3.2.3 on 2022-12-09 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='user name')),
                ('code', models.CharField(max_length=50, verbose_name='user code')),
                ('is_active', models.BooleanField(default=True, verbose_name='user is active')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('time_updated', models.DateTimeField(auto_now=True, verbose_name='updated time')),
            ],
        ),
    ]
