# Generated by Django 3.2.3 on 2022-12-09 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-time_updated'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
